<?php

array_walk(
 glob(dirname(__FILE__) . '/inc/*'),
 create_function('$v,$i', 'return require_once($v);')
); 

function islandora_dm_init() {
  drupal_add_css(drupal_get_path('module', 'islandora_dm') .'/css/islandora-dm.css');
}

/**
 * TODO: Display help and module information.
 */
function islandora_dm_help($path, $arg) {
  $output = '';
  
  switch ($path) {
    case "admin/help#islandora_dm":
      $output = '<p>' . t("todo: implement help text") . '</p>';
      break;
  }
  
  return $output;
}

/**
 * Valid permissions for this module.
 */
function islandora_dm_perm() {
  return array(
    // configure module settings
    'admin islandora_dm', 
    
    // view module pages and documents (subject to fedora authorization)
    'access islandora_dm',
    
    // import new documents
    'import islandora_dm' 
    );
}

function islandora_dm_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_dm_import_files_checkboxes' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}